package com.sadad.common.errors;

import lombok.Getter;

import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Every error this platform can report, with the wording it falls back to.
 *
 * <p><b>Why the codes live in code and the wording lives in data.</b> This mirrors the
 * split the platform already uses for permissions, and for the same reasons. The SET of
 * codes is a contract between services, the admin console and both portals: it must be
 * checkable at compile time, because a mistyped code is not a compile error anywhere else -
 * it silently produces an untranslated message that only the customer ever sees. The WORDING
 * is editorial. It gets revised by people who are not deploying software, it differs per
 * language, and it must be changeable on a Tuesday afternoon without a release. So the codes
 * are here and the text is in {@code error_catalog_entries}, editable in the admin console,
 * with these values as the seed and the permanent fallback.
 *
 * <p><b>Every code carries both languages.</b> Not because the database is unreliable, but
 * because the failure path must not have a dependency. A service that cannot reach
 * saddad-admin - during a cold start, a deploy, or an outage - still has to tell a customer
 * what went wrong, in their language. A catalogue that only lived in the database would be
 * unreachable at precisely the moment it is most needed.
 *
 * <p><b>On the Arabic.</b> These are written as a Saudi corporate user would expect to read
 * them, not as transliterated English. Numbers, reference numbers and IBANs stay in Latin
 * digits in both languages, matching the rest of the platform, because those are values a
 * user reads back to a support agent.
 *
 * <p><b>Placeholders</b> are {@code {named}} and are listed in {@link #params} so a guard
 * test can check that both translations use exactly the declared set - a placeholder present
 * in English and missing in Arabic is a fact silently dropped for Arabic readers.
 */
@Getter
public enum ErrorCode {

    // ---------------------------------------------------------------- generic / transport
    VALIDATION_ERROR(400, "VALIDATION", "WARN",
            "Some of the information provided is not valid. Please check and try again.",
            "بعض البيانات المُدخلة غير صحيحة. يرجى التحقق والمحاولة مرة أخرى."),
    BUSINESS_RULE_VIOLATION(422, "BUSINESS", "WARN",
            "This action cannot be completed in the current state.",
            "لا يمكن إتمام هذا الإجراء في الوضع الحالي."),
    RESOURCE_NOT_FOUND(404, "GENERAL", "WARN",
            "The requested item was not found.",
            "العنصر المطلوب غير موجود."),
    RESOURCE_CONFLICT(409, "GENERAL", "WARN",
            "This conflicts with something that already exists.",
            "يتعارض هذا مع عنصر موجود بالفعل."),
    FORBIDDEN_ACCESS(403, "SECURITY", "WARN",
            "You do not have permission to perform this action.",
            "لا تملك صلاحية تنفيذ هذا الإجراء."),
    ACCESS_DENIED(403, "SECURITY", "WARN",
            "You do not have permission to perform this action.",
            "لا تملك صلاحية تنفيذ هذا الإجراء."),
    UPSTREAM_INTEGRATION_ERROR(502, "INTEGRATION", "ERROR",
            "A service we rely on is not responding. Please try again shortly.",
            "إحدى الخدمات المرتبطة لا تستجيب حالياً. يرجى المحاولة بعد قليل."),
    INTERNAL_SERVER_ERROR(500, "GENERAL", "CRITICAL",
            "Something went wrong on our side. The issue has been logged.",
            "حدث خطأ لدينا. تم تسجيل المشكلة لمراجعتها."),
    ROUTE_NOT_FOUND(404, "GENERAL", "WARN",
            "The requested address does not exist.",
            "العنوان المطلوب غير موجود."),
    MISSING_TENANT_CONTEXT(401, "SECURITY", "CRITICAL",
            "Your session has ended. Please sign in again.",
            "انتهت جلستك. يرجى تسجيل الدخول مرة أخرى."),
    SESSION_SUPERSEDED(401, "SECURITY", "WARN",
            "Your session is no longer active. You may have signed in elsewhere, or signed out.",
            "لم تعد جلستك نشطة. ربما سجّلت الدخول من جهاز آخر أو قمت بتسجيل الخروج."),
    UNAUTHENTICATED(401, "SECURITY", "WARN",
            "Please sign in to continue.",
            "يرجى تسجيل الدخول للمتابعة."),
    TEMPLATE_RENDER_FAILED(500, "GENERAL", "ERROR", false,
            "A message could not be prepared. The issue has been logged.",
            "تعذّر تجهيز الرسالة. تم تسجيل المشكلة لمراجعتها."),
    METHOD_NOT_ALLOWED(405, "GENERAL", "WARN",
            "{method} is not accepted at this address. Supported: {supported}.",
            "الطريقة {method} غير مقبولة على هذا العنوان. المسموح: {supported}.", "method", "supported"),
    UNSUPPORTED_MEDIA_TYPE(415, "GENERAL", "WARN",
            "This content type is not supported.",
            "نوع المحتوى غير مدعوم."),
    MALFORMED_REQUEST_BODY(400, "VALIDATION", "WARN",
            "The request could not be read. Please try again.",
            "تعذّرت قراءة الطلب. يرجى المحاولة مرة أخرى."),
    MISSING_PARAMETER(400, "VALIDATION", "WARN",
            "'{parameter}' is required.",
            "الحقل '{parameter}' مطلوب.", "parameter"),
    PARAMETER_TYPE_MISMATCH(400, "VALIDATION", "WARN",
            "'{parameter}' is not in the expected format.",
            "قيمة الحقل '{parameter}' ليست بالصيغة المتوقعة.", "parameter"),
    FILE_TOO_LARGE(413, "VALIDATION", "WARN",
            "This file is too large. Please upload a file under {limit}.",
            "حجم الملف كبير جداً. يرجى رفع ملف أصغر من {limit}.", "limit"),
    INVALID_STATE_TRANSITION(422, "BUSINESS", "WARN",
            "This item cannot move from {from} to {to}.",
            "لا يمكن نقل هذا العنصر من {from} إلى {to}.", "from", "to"),

    TENANT_NOT_FOUND(404, "GENERAL", "WARN",
            "This organization was not found.",
            "لم يتم العثور على هذه المنشأة."),
    USER_NOT_FOUND(404, "ADMIN", "WARN",
            "This user was not found.",
            "لم يتم العثور على هذا المستخدم."),
    ROLE_NOT_FOUND(404, "ADMIN", "WARN",
            "This role was not found.",
            "لم يتم العثور على هذا الدور."),
    LOV_NOT_FOUND(404, "ADMIN", "WARN",
            "This list of values was not found.",
            "لم يتم العثور على هذه القائمة."),
    FLAG_NOT_FOUND(404, "ADMIN", "WARN",
            "This feature flag was not found.",
            "لم يتم العثور على هذه الخاصية."),
    CONTENT_NOT_FOUND(404, "ADMIN", "WARN",
            "This content block was not found.",
            "لم يتم العثور على هذا المحتوى."),
    ERROR_CODE_NOT_FOUND(404, "ADMIN", "WARN",
            "This error code is not in the catalogue.",
            "رمز الخطأ هذا غير موجود في الفهرس."),
    INVITATION_NOT_FOUND(404, "ADMIN", "WARN",
            "This invitation was not found.",
            "لم يتم العثور على هذه الدعوة."),
    INVITATION_LINK_INVALID(400, "ADMIN", "WARN",
            "This invitation link is no longer valid. Please ask an administrator for a new one.",
            "لم يعد رابط الدعوة صالحاً. يرجى طلب رابط جديد من المسؤول."),
    FEEDBACK_NOT_FOUND(404, "GENERAL", "WARN",
            "This ticket was not found.",
            "لم يتم العثور على هذه التذكرة."),
    NOTIFICATION_NOT_FOUND(404, "GENERAL", "WARN",
            "This notification was not found.",
            "لم يتم العثور على هذا الإشعار."),
    PERMISSION_UNKNOWN(400, "ADMIN", "WARN",
            "'{permission}' is not a permission this platform defines.",
            "الصلاحية '{permission}' غير معرّفة في المنصة.", "permission"),
    INTEGRATION_PROVIDER_NOT_FOUND(404, "ADMIN", "WARN",
            "This integration provider was not found.",
            "لم يتم العثور على مزوّد التكامل هذا."),
    INTEGRATION_ENDPOINT_NOT_FOUND(404, "ADMIN", "WARN",
            "This integration endpoint was not found.",
            "لم يتم العثور على مسار التكامل هذا."),
    INTEGRATION_SCENARIO_NOT_FOUND(404, "ADMIN", "WARN",
            "This mock scenario was not found.",
            "لم يتم العثور على سيناريو المحاكاة هذا."),
    MAIL_BODY_FORMAT_INVALID(400, "ADMIN", "WARN",
            "A message body must be either plain text or HTML.",
            "يجب أن يكون نص الرسالة إمّا نصاً عادياً أو HTML."),
    OTP_LENGTH_OUT_OF_RANGE(400, "ADMIN", "WARN",
            "The code length must be between 4 and 8 digits.",
            "يجب أن يكون طول الرمز بين 4 و8 أرقام."),
    OTP_TEMPLATE_REQUIRED(400, "ADMIN", "WARN",
            "Enter the message text that carries the code.",
            "أدخل نص الرسالة التي تحمل الرمز."),
    OTP_EXPIRY_OUT_OF_RANGE(400, "ADMIN", "WARN",
            "The code lifetime must be between 30 and 900 seconds. Below 30 there is no time to read the message; above 900 it stops being a one-time code.",
            "يجب أن تكون مدة صلاحية الرمز بين 30 و900 ثانية. أقل من 30 لا تكفي لقراءة الرسالة، وأكثر من 900 تُفقد الرمز خاصيته المؤقتة."),
    OTP_TRIALS_OUT_OF_RANGE(400, "ADMIN", "WARN",
            "The number of allowed attempts must be between 1 and 10.",
            "يجب أن يكون عدد المحاولات المسموح بها بين 1 و10."),
    OTP_LOCK_OUT_OF_RANGE(400, "ADMIN", "WARN",
            "The lock duration must be between 1 minute and 24 hours.",
            "يجب أن تكون مدة القفل بين دقيقة واحدة و24 ساعة."),
    OTP_COOLDOWN_OUT_OF_RANGE(400, "ADMIN", "WARN",
            "The resend wait must be between 0 and 600 seconds.",
            "يجب أن تكون مدة انتظار إعادة الإرسال بين 0 و600 ثانية."),
    OTP_SENDS_OUT_OF_RANGE(400, "ADMIN", "WARN",
            "The send ceiling must be between 1 and 50 messages.",
            "يجب أن يكون حد الإرسال بين رسالة واحدة و50 رسالة."),
    OTP_EXPIRED(400, "AUTH", "WARN",
            "That code has expired. Ask for a new one and enter it within the time shown.",
            "انتهت صلاحية الرمز. اطلب رمزاً جديداً وأدخله خلال المدة المعروضة."),
    OTP_LOCKED(423, "AUTH", "WARN",
            "Too many incorrect codes. Your account is locked for {minutes} minutes; please try again after that.",
            "عدد كبير من المحاولات الخاطئة. تم قفل الحساب لمدة {minutes} دقيقة، يرجى المحاولة بعدها.",
            "minutes"),
    OTP_RESEND_TOO_SOON(429, "AUTH", "WARN",
            "A code was just sent. You can ask for another in {seconds} seconds.",
            "تم إرسال رمز للتو. يمكنك طلب رمز آخر بعد {seconds} ثانية.",
            "seconds"),
    INTEGRATION_CREDENTIAL_REQUIRED(400, "ADMIN", "WARN",
            "Enter the credential to store.",
            "أدخل بيانات الاعتماد المراد حفظها."),
    INTEGRATION_CREDENTIAL_TOO_LONG(400, "ADMIN", "WARN",
            "That credential is longer than this platform stores. Check it was pasted correctly.",
            "بيانات الاعتماد أطول مما تحفظه المنصة. تأكّد من لصقها بشكل صحيح."),
    INTEGRATION_CREDENTIAL_MISSING(503, "INTEGRATION", "CRITICAL", false,
            "No credential is stored for {provider}. Set one in the integrations console before leaving simulation.",
            "لا توجد بيانات اعتماد محفوظة للمزوّد {provider}. أضفها من شاشة التكاملات قبل الخروج من وضع المحاكاة.",
            "provider"),
    INTEGRATION_PROVIDER_NOT_CONFIGURED(503, "INTEGRATION", "CRITICAL", false,
            "The {provider} provider is not configured.",
            "مزوّد الخدمة {provider} غير مُعدّ.", "provider"),
    INTEGRATION_ENDPOINT_NOT_CONFIGURED(503, "INTEGRATION", "CRITICAL", false,
            "The '{endpoint}' endpoint is not configured for {provider}.",
            "المسار '{endpoint}' غير مُعدّ لدى المزوّد {provider}.", "endpoint", "provider"),
    AUTOMATION_ENGINE_DISABLED(422, "ADMIN", "WARN",
            "The automation engine is switched off platform-wide.",
            "محرك الأتمتة معطّل على مستوى المنصة."),
    // Field-level validation an applicant sees against the input itself. These are used as
    // Bean Validation `message` values, so the annotation names a code and the handler
    // renders it in the reader's language - see GlobalExceptionHandler.
    ONB_ID_NUMBER_FORMAT(400, "ONBOARDING", "WARN",
            "The ID number must be 10 digits, starting with 1 for a National ID or 2 for an Iqama.",
            "رقم الهوية يجب أن يكون 10 أرقام، يبدأ بـ 1 للهوية الوطنية أو 2 للإقامة."),
    ONB_CR_NUMBER_FORMAT(400, "ONBOARDING", "WARN",
            "The Commercial Registration number must be 10 digits, starting with 10.",
            "رقم السجل التجاري يجب أن يكون 10 أرقام، ويبدأ بـ 10."),
    ONB_MOBILE_FORMAT(400, "ONBOARDING", "WARN",
            "The mobile number must be 10 digits, starting with 05.",
            "رقم الجوال يجب أن يكون 10 أرقام، ويبدأ بـ 05."),
    ONB_EMAIL_FORMAT(400, "ONBOARDING", "WARN",
            "Please enter a valid email address.",
            "يرجى إدخال بريد إلكتروني صحيح."),
    ONB_USERNAME_FORMAT(400, "ONBOARDING", "WARN",
            "The username must be 4 to 32 characters: letters, numbers, dot, underscore or hyphen, with no spaces.",
            "اسم المستخدم من 4 إلى 32 خانة: أحرف وأرقام ونقطة وشرطة سفلية أو شرطة، بدون مسافات."),
    ONB_ID_TYPE_UNKNOWN(400, "ONBOARDING", "WARN",
            "This identity document type is not recognised.",
            "نوع وثيقة الهوية هذا غير معروف."),

    // ------------------------------------------------------------------ sign-in / identity
    AUTH_INVALID_CREDENTIALS(401, "SECURITY", "WARN",
            "Invalid Commercial Registration number, National ID, or credentials.",
            "رقم السجل التجاري أو الهوية الوطنية أو بيانات الدخول غير صحيحة."),
    AUTH_ACCOUNT_DISABLED(403, "SECURITY", "WARN",
            "This account has been disabled. Please contact your administrator.",
            "تم تعطيل هذا الحساب. يرجى التواصل مع مسؤول النظام."),
    AUTH_ACCOUNT_DISABLED_PLATFORM(403, "SECURITY", "WARN",
            "This account has been disabled. Contact another platform administrator.",
            "تم تعطيل هذا الحساب. يرجى التواصل مع مسؤول منصة آخر."),
    AUTH_NO_SESSION(401, "SECURITY", "WARN",
            "Your session has ended. Please sign in again.",
            "انتهت جلستك. يرجى تسجيل الدخول مرة أخرى."),
    AUTH_OTP_INVALID(400, "SECURITY", "WARN",
            "The verification code is incorrect or has expired.",
            "رمز التحقق غير صحيح أو انتهت صلاحيته."),
    AUTH_VERIFICATION_NOT_INITIATED(400, "SECURITY", "WARN",
            "Request a verification code before confirming one.",
            "يرجى طلب رمز التحقق أولاً قبل تأكيده."),
    AUTH_TOO_MANY_ATTEMPTS(429, "SECURITY", "WARN",
            "Too many attempts. Please wait {minutes} minutes and try again.",
            "عدد المحاولات تجاوز الحد المسموح. يرجى الانتظار {minutes} دقيقة والمحاولة مرة أخرى.", "minutes"),
    AUTH_OTP_LOGIN_UNAVAILABLE(422, "SECURITY", "WARN",
            "One-time-code sign-in is not available for this account.",
            "تسجيل الدخول برمز التحقق غير متاح لهذا الحساب."),
    AUTH_PASSWORD_LOGIN_REQUIRED(400, "SECURITY", "WARN",
            "This account signs in with its username and password.",
            "يتم تسجيل الدخول لهذا الحساب باسم المستخدم وكلمة المرور."),
    AUTH_OTP_LOGIN_REQUIRED(400, "SECURITY", "WARN",
            "This account signs in with a one-time code sent to its registered mobile number.",
            "يتم تسجيل الدخول لهذا الحساب برمز تحقق يُرسل إلى رقم الجوال المسجّل."),
    AUTH_PASSWORD_MISMATCH(400, "VALIDATION", "WARN",
            "The password and its confirmation do not match.",
            "كلمة المرور وتأكيدها غير متطابقين."),
    AUTH_PASSWORD_TOO_WEAK(400, "VALIDATION", "WARN",
            "The password must be at least {minLength} characters and include an uppercase letter, "
                    + "a lowercase letter, a digit, and a special character.",
            "يجب ألا تقل كلمة المرور عن {minLength} أحرف، وأن تتضمن حرفاً كبيراً وحرفاً صغيراً "
                    + "ورقماً ورمزاً خاصاً.", "minLength"),
    AUTH_CURRENT_PASSWORD_INCORRECT(400, "VALIDATION", "WARN",
            "The current password is not correct.",
            "كلمة المرور الحالية غير صحيحة."),
    AUTH_NEW_PASSWORD_NOT_CHANGED(400, "VALIDATION", "WARN",
            "The new password must be different from the current one.",
            "يجب أن تختلف كلمة المرور الجديدة عن الحالية."),
    AUTH_PLAINTEXT_CREDENTIAL_REJECTED(400, "SECURITY", "ERROR", false,
            "'{field}' must be derived in the browser before it is sent.",
            "يجب اشتقاق الحقل '{field}' في المتصفح قبل إرساله.", "field"),
    AUTH_SIMULATED_SIGN_IN_UNAVAILABLE(422, "SECURITY", "WARN",
            "Simulated sign-in is only available while integrations run in mock mode.",
            "تسجيل الدخول المحاكى متاح فقط أثناء تشغيل التكاملات في وضع المحاكاة."),
    AUTH_TENANT_SCOPE_VIOLATION(403, "SECURITY", "ERROR",
            "You may only manage users within your own organization.",
            "يمكنك إدارة المستخدمين ضمن منشأتك فقط."),
    AUTH_MOBILE_REQUIRED_FOR_ROLE(400, "VALIDATION", "WARN",
            "A mobile number is required for {role} accounts, for one-time-code sign-in.",
            "رقم الجوال مطلوب لحسابات {role} لاستخدامه في تسجيل الدخول برمز التحقق.", "role"),

    // ------------------------------------------------------------------------- onboarding
    ONB_APPLICATION_NOT_EDITABLE(422, "ONBOARDING", "WARN",
            "This application can no longer be edited in its current status.",
            "لا يمكن تعديل هذا الطلب في حالته الحالية."),
    ONB_APPLICATION_NOT_FOUND(404, "ONBOARDING", "WARN",
            "We could not find this application.",
            "لم نتمكن من العثور على هذا الطلب."),
    ONB_DUPLICATE_APPLICATION(409, "ONBOARDING", "WARN",
            "An application for this Commercial Registration is already in progress.",
            "يوجد طلب قيد المعالجة لهذا السجل التجاري بالفعل."),
    ONB_IDENTITY_STEP_REQUIRED(400, "ONBOARDING", "WARN",
            "Please complete the Identity step first.",
            "يرجى إكمال خطوة الهوية أولاً."),
    ONB_IDENTITY_VERIFICATION_REQUIRED(400, "ONBOARDING", "WARN",
            "Identity verification must be completed before requesting a verification code.",
            "يجب إكمال التحقق من الهوية قبل طلب رمز التحقق."),
    ONB_MOBILE_VERIFICATION_REQUIRED(400, "ONBOARDING", "WARN",
            "Mobile verification must be completed before company verification.",
            "يجب إكمال التحقق من رقم الجوال قبل التحقق من المنشأة."),
    ONB_COMPANY_VERIFICATION_REQUIRED(400, "ONBOARDING", "WARN",
            "Company verification must be completed before the Bank step.",
            "يجب إكمال التحقق من المنشأة قبل خطوة الحساب البنكي."),
    ONB_PRIOR_STEPS_REQUIRED(400, "ONBOARDING", "WARN",
            "All previous steps must be completed before setting your credentials.",
            "يجب إكمال جميع الخطوات السابقة قبل إنشاء بيانات الدخول."),
    ONB_MOBILE_NOT_OWNED(400, "ONBOARDING", "WARN",
            "This mobile number does not appear to be registered to the ID number provided. "
                    + "Please check both and try again.",
            "رقم الجوال هذا غير مسجّل باسم رقم الهوية المُدخل. يرجى التحقق من الرقمين والمحاولة مرة أخرى."),
    ONB_MOBILE_ALREADY_REGISTERED(409, "ONBOARDING", "WARN",
            "This mobile number is already registered to another organization.",
            "رقم الجوال هذا مسجّل لدى منشأة أخرى."),
    ONB_NOT_AUTHORIZED_MANAGER(400, "ONBOARDING", "WARN",
            "This ID number is not registered as an authorized manager of this Commercial Registration.",
            "رقم الهوية هذا غير مسجّل كمدير مفوّض لهذا السجل التجاري."),
    ONB_CR_NOT_ACTIVE(400, "ONBOARDING", "WARN",
            "This Commercial Registration is not currently active (status: {status}).",
            "هذا السجل التجاري غير نشط حالياً (الحالة: {status}).", "status"),
    ONB_CR_VALIDATION_FAILED(400, "ONBOARDING", "WARN",
            "This Commercial Registration number could not be validated.",
            "تعذّر التحقق من رقم السجل التجاري."),
    ONB_USERNAME_TAKEN(409, "ONBOARDING", "WARN",
            "This username is already taken. Please choose another.",
            "اسم المستخدم هذا مستخدم بالفعل. يرجى اختيار اسم آخر."),
    ONB_IBAN_INVALID(400, "ONBOARDING", "WARN",
            "Please enter a valid Saudi IBAN: 24 characters beginning with SA.",
            "يرجى إدخال رقم آيبان سعودي صحيح مكوّن من 24 خانة ويبدأ بـ SA."),
    ONB_IBAN_BANK_NOT_ACCEPTED(400, "ONBOARDING", "WARN",
            "Only an IBAN from {bankName} is accepted. Please open an account there and try again.",
            "يُقبل فقط آيبان صادر من {bankName}. يرجى فتح حساب لديه والمحاولة مرة أخرى.", "bankName"),
    ONB_IBAN_AUTO_GENERATION_DISABLED(422, "ONBOARDING", "WARN",
            "Automatic IBAN generation is switched off. Please enter your IBAN.",
            "إنشاء الآيبان تلقائياً غير مفعّل. يرجى إدخال رقم الآيبان الخاص بك."),
    ONB_IBAN_GENERATION_UNAVAILABLE(502, "ONBOARDING", "ERROR",
            "The IBAN service is unavailable right now. Please enter your IBAN instead.",
            "خدمة إنشاء الآيبان غير متاحة حالياً. يرجى إدخال رقم الآيبان يدوياً."),
    ONB_TOO_MANY_ATTEMPTS(429, "ONBOARDING", "WARN",
            "Too many attempts. Please wait {minutes} minutes and try again.",
            "عدد المحاولات تجاوز الحد المسموح. يرجى الانتظار {minutes} دقيقة والمحاولة مرة أخرى.", "minutes"),

    // ------------------------------------------------------------- upstream integrations
    INTEGRATION_NOT_CONFIGURED(503, "INTEGRATION", "CRITICAL", false,
            "{service} is not fully configured. Please contact support.",
            "خدمة {service} غير مكتملة الإعداد. يرجى التواصل مع الدعم.", "service"),
    INTEGRATION_URL_MISSING(503, "INTEGRATION", "CRITICAL", false,
            "No {mode} address is configured for {endpoint}. An administrator must set one first.",
            "لا يوجد عنوان مُعرَّف لوضع {mode} للخدمة {endpoint}. يجب على المسؤول تعيينه أولاً.",
            "mode", "endpoint"),
    INTEGRATION_UNAVAILABLE(502, "INTEGRATION", "ERROR",
            "{service} is temporarily unavailable. Please try again shortly.",
            "خدمة {service} غير متاحة مؤقتاً. يرجى المحاولة بعد قليل.", "service"),
    INTEGRATION_EMPTY_RESPONSE(502, "INTEGRATION", "ERROR",
            "{service} returned an empty response.",
            "لم تُرجع خدمة {service} أي بيانات.", "service"),
    INTEGRATION_INVALID_RESPONSE(502, "INTEGRATION", "ERROR",
            "{service} returned a response we could not use.",
            "أرجعت خدمة {service} استجابة غير صالحة.", "service"),
    GOV_INTEGRATION_TIMEOUT(504, "INTEGRATION", "CRITICAL",
            "The government authority's service timed out.",
            "انتهت مهلة الاستجابة من بوابة الجهة الحكومية."),
    PROVISIONING_UNAVAILABLE(502, "INTEGRATION", "ERROR",
            "Account setup is temporarily unavailable. Please try again shortly.",
            "خدمة تفعيل الحساب غير متاحة مؤقتاً. يرجى المحاولة بعد قليل."),

    // ------------------------------------------------------------------- wallet & payment
    WALLET_INSUFFICIENT_FUNDS(422, "PAYMENT", "ERROR",
            "The wallet balance is not enough to settle {reference}. Please top up and try again.",
            "رصيد المحفظة غير كافٍ لسداد {reference}. يرجى شحن المحفظة والمحاولة مرة أخرى.", "reference"),
    WALLET_IBAN_INVALID(400, "PAYMENT", "WARN",
            "Please enter a valid Saudi IBAN: 24 characters beginning with SA.",
            "يرجى إدخال رقم آيبان سعودي صحيح مكوّن من 24 خانة ويبدأ بـ SA."),
    WALLET_DEBIT_FAILED(502, "PAYMENT", "CRITICAL",
            "The wallet could not be charged. No money has been taken.",
            "تعذّر الخصم من المحفظة. لم يتم خصم أي مبلغ."),
    WALLET_REVERSAL_FAILED(502, "PAYMENT", "CRITICAL",
            "A refund to the wallet could not be completed automatically. Support has been notified.",
            "تعذّر إتمام إعادة المبلغ إلى المحفظة تلقائياً. تم إبلاغ الدعم الفني."),
    PAYMENT_DECLINED(422, "PAYMENT", "ERROR",
            "The payment was declined: {reason}",
            "تم رفض عملية الدفع: {reason}", "reason"),
    PAYMENT_GATEWAY_DECLINED(422, "PAYMENT", "ERROR",
            "The bank declined this payment: {reason}",
            "رفض البنك عملية الدفع: {reason}", "reason"),
    WALLET_NOT_ACTIVE(409, "PAYMENT", "WARN",
            "This wallet is not active yet, so it cannot be used to pay. Current status: {status}.",
            "هذه المحفظة غير مفعّلة بعد، ولا يمكن استخدامها للدفع. الحالة الحالية: {status}.", "status"),
    PAYMENT_METHOD_NOT_FOUND(404, "PAYMENT", "WARN",
            "That payment method is not recognised.",
            "طريقة الدفع غير معروفة."),
    PAYMENT_METHOD_UNAVAILABLE(409, "PAYMENT", "WARN",
            "{method} is not available at the moment. Please choose another payment method.",
            "{method} غير متاحة حالياً. يرجى اختيار طريقة دفع أخرى.", "method"),
    PAYMENT_AMOUNT_OUT_OF_RANGE(400, "PAYMENT", "WARN",
            "This payment method accepts amounts between {min} and {max} SAR.",
            "تقبل طريقة الدفع هذه المبالغ بين {min} و{max} ريال.", "min", "max"),
    WALLET_BALANCE_INQUIRY_UNAVAILABLE(503, "PAYMENT", "WARN",
            "The linked bank account could not be reached for a balance update. The balance shown may not be current.",
            "تعذّر الوصول إلى الحساب البنكي المرتبط لتحديث الرصيد. قد لا يكون الرصيد المعروض محدثاً."),
    SAVED_CARD_NOT_FOUND(404, "PAYMENT", "WARN",
            "That saved card is no longer available. Please choose another card.",
            "البطاقة المحفوظة لم تعد متاحة. يرجى اختيار بطاقة أخرى."),
    SAVED_CARD_LIMIT_REACHED(409, "PAYMENT", "WARN",
            "You can keep up to {limit} cards. Please remove one before adding another.",
            "يمكنك الاحتفاظ بحد أقصى {limit} بطاقات. يرجى حذف إحداها قبل إضافة بطاقة جديدة.", "limit"),
    SAVED_CARD_DETAILS_REJECTED(400, "PAYMENT", "WARN",
            "Those card details could not be saved. Please add the card again.",
            "تعذّر حفظ بيانات البطاقة. يرجى إضافة البطاقة مرة أخرى."),
    AUTO_RELOAD_METHOD_REQUIRED(400, "PAYMENT", "WARN",
            "Choose where automatic reloads should be funded from before switching them on.",
            "اختر مصدر تمويل إعادة الشحن التلقائي قبل تفعيلها."),
    AUTO_RELOAD_METHOD_NOT_ALLOWED(409, "PAYMENT", "WARN",
            "{method} cannot be used for automatic reloads. Please choose another source.",
            "لا يمكن استخدام {method} لإعادة الشحن التلقائي. يرجى اختيار مصدر آخر.", "method"),
    AUTO_RELOAD_CARD_REQUIRED(400, "PAYMENT", "WARN",
            "Choose which saved card should fund automatic reloads.",
            "اختر البطاقة المحفوظة التي ستموّل إعادة الشحن التلقائي."),
    AUTO_RELOAD_SOURCE_INSUFFICIENT(409, "PAYMENT", "WARN",
            "Your linked account holds {available} SAR, which is less than the {amount} SAR reload you have set. "
                    + "Lower the reload amount or fund the account first.",
            "يحتوي حسابك المرتبط على {available} ريال، وهو أقل من مبلغ إعادة الشحن المحدد {amount} ريال. "
                    + "يرجى تقليل المبلغ أو تغذية الحساب أولاً.", "available", "amount"),
    AUTO_RELOAD_AMOUNT_TOO_LOW(400, "PAYMENT", "WARN",
            "The reload amount must be more than the {threshold} SAR threshold, otherwise the balance would "
                    + "still be below it after reloading.",
            "يجب أن يكون مبلغ إعادة الشحن أكبر من الحد الأدنى {threshold} ريال، وإلا سيظل الرصيد أقل منه بعد الشحن.",
            "threshold"),
    AUTO_RELOAD_CHARGE_FAILED(502, "PAYMENT", "CRITICAL",
            "An automatic reload could not be funded: {reason}. Your balance has not changed.",
            "تعذّر تمويل إعادة الشحن التلقائي: {reason}. لم يتغيّر رصيدك.", "reason"),
    PAYMENT_METHOD_NOT_SELF_SERVICE(409, "PAYMENT", "WARN",
            "A bank transfer is credited when the funds reach the account - it cannot be confirmed from here. "
                    + "Your balance updates automatically once the transfer clears.",
            "تتم إضافة الحوالة البنكية عند وصول المبلغ إلى الحساب، ولا يمكن تأكيدها من هنا. "
                    + "سيتم تحديث رصيدك تلقائياً بمجرد اكتمال التحويل."),

    // -------------------------------------------------------------- violations/obligations
    OBLIGATION_NOT_FOUND(404, "OBLIGATION", "WARN",
            "The requested government obligation was not found.",
            "المستحق الحكومي المطلوب غير موجود بالسجل."),

    // ---------------------------------------------------------------------------- employees
    EMPLOYEE_DUPLICATE_ID(409, "EMPLOYEE", "WARN",
            "This Iqama or National ID is already registered.",
            "رقم الهوية أو الإقامة هذا مسجّل بالفعل."),
    EMPLOYEE_FILE_EMPTY(400, "EMPLOYEE", "WARN",
            "The uploaded file is empty.",
            "الملف المرفوع فارغ."),
    EMPLOYEE_FILE_UNREADABLE(400, "EMPLOYEE", "WARN",
            "We could not read this file. Please make sure it is a valid .xlsx file.",
            "تعذّرت قراءة هذا الملف. يرجى التأكد من أنه ملف .xlsx صالح."),
    EMPLOYEE_FILE_FORMAT_INVALID(400, "EMPLOYEE", "WARN",
            "We could not process this file. Please check it matches the downloaded template.",
            "تعذّرت معالجة هذا الملف. يرجى التأكد من مطابقته للقالب المُنزّل."),

    // ------------------------------------------------------------------ tenant provisioning
    TENANT_ALREADY_EXISTS(409, "ONBOARDING", "WARN",
            "An organization with this Commercial Registration number already exists.",
            "توجد منشأة مسجّلة بهذا الرقم للسجل التجاري بالفعل."),

    // ------------------------------------------------------- admin console: users & roles
    USER_ALREADY_EXISTS(409, "ADMIN", "WARN",
            "A user with this login already exists.",
            "يوجد مستخدم بهذا المعرّف بالفعل."),
    USER_CANNOT_DISABLE_SELF(422, "ADMIN", "WARN",
            "You cannot disable your own account.",
            "لا يمكنك تعطيل حسابك الخاص."),
    USER_LAST_PLATFORM_ADMIN(422, "ADMIN", "ERROR",
            "This is the last platform administrator. Grant the role to someone else first.",
            "هذا آخر مسؤول للمنصة. يرجى منح الصلاحية لمستخدم آخر أولاً."),
    ROLE_ALREADY_EXISTS(409, "ADMIN", "WARN",
            "A role with this name already exists.",
            "يوجد دور بهذا الاسم بالفعل."),
    ROLE_IN_USE(422, "ADMIN", "WARN",
            "This role is assigned to {count} user(s) and cannot be deleted.",
            "هذا الدور مُسند إلى {count} مستخدم ولا يمكن حذفه.", "count"),
    ROLE_SYSTEM_IMMUTABLE(422, "ADMIN", "WARN",
            "This is a built-in role and cannot be changed.",
            "هذا دور مدمج في النظام ولا يمكن تعديله."),
    ROLE_NEEDS_AT_LEAST_ONE_PERMISSION(400, "ADMIN", "WARN",
            "A role must grant at least one permission.",
            "يجب أن يمنح الدور صلاحية واحدة على الأقل."),
    ROLE_MISSING_VIEW_PERMISSION(400, "ADMIN", "WARN",
            "Add {permissions} - a role cannot act on an area it cannot open.",
            "يرجى إضافة {permissions} - لا يمكن للدور التعديل على قسم لا يستطيع فتحه.", "permissions"),
    ROLE_UNKNOWN(400, "ADMIN", "WARN",
            "'{role}' is not a role this platform knows.",
            "الدور '{role}' غير معروف في المنصة.", "role"),
    ROLE_TENANT_REQUIRED(400, "ADMIN", "WARN",
            "An organization must be chosen for a tenant role.",
            "يجب اختيار المنشأة عند إنشاء دور خاص بالمنشآت."),
    INVITATION_ALREADY_PENDING(409, "ADMIN", "WARN",
            "An invitation for this email is already pending.",
            "توجد دعوة معلّقة لهذا البريد الإلكتروني بالفعل."),
    INVITATION_ALREADY_ACCEPTED(409, "ADMIN", "WARN",
            "This invitation has already been accepted.",
            "تم قبول هذه الدعوة بالفعل."),
    INVITATION_NOT_PENDING(422, "ADMIN", "WARN",
            "This invitation is no longer pending.",
            "لم تعد هذه الدعوة معلّقة."),

    // ----------------------------------------------- admin console: configuration & content
    FLAG_ALREADY_EXISTS(409, "ADMIN", "WARN",
            "A feature flag with this key already exists.",
            "توجد خاصية بهذا المُعرِّف بالفعل."),
    ERROR_CODE_ALREADY_EXISTS(409, "ADMIN", "WARN",
            "This error code is already in the catalogue.",
            "رمز الخطأ هذا موجود في الفهرس بالفعل."),
    CARD_TOKENISATION_REFUSED(422, "PAYMENT", "WARN",
            "The card could not be added: {reason}",
            "تعذّرت إضافة البطاقة: {reason}",
            "reason"),
    SIMULATION_REQUEST_REFUSED(422, "ADMIN", "WARN",
            "The simulated violation was refused - check the biller and the amount.",
            "تم رفض المخالفة التجريبية - تحقق من الجهة والمبلغ."),
    REPORT_PERIOD_INVALID(400, "ADMIN", "WARN",
            "Choose a period that ends on or after it starts and covers at most {maxDays} days.",
            "اختر فترة تنتهي في تاريخ البداية أو بعده ولا تتجاوز {maxDays} يوماً.",
            "maxDays"),
    SADAD_BILLER_NOT_FOUND(404, "ADMIN", "WARN",
            "No registered biller with id {billerId}. Refresh the biller list and try again.",
            "لا توجد جهة مسجَّلة بالرمز {billerId}. حدِّث قائمة الجهات ثم أعد المحاولة.",
            "billerId"),
    SIMULATION_REFERENCE_EXHAUSTED(500, "ADMIN", "ERROR",
            "Could not allocate a unique reference for the simulated violation. Please try again.",
            "تعذر إنشاء مرجع فريد للمخالفة التجريبية. يرجى المحاولة مرة أخرى."),
    CONTENT_SLUG_EXISTS(409, "ADMIN", "WARN",
            "A content block with this slug already exists.",
            "يوجد محتوى بهذا المُعرِّف بالفعل."),
    CONTENT_WINDOW_INVALID(422, "ADMIN", "WARN",
            "The display window ends before it starts, so this content could never appear.",
            "فترة العرض تنتهي قبل أن تبدأ، ولن يظهر هذا المحتوى إطلاقاً."),
    LOV_TYPE_EXISTS(409, "ADMIN", "WARN",
            "A list with this code already exists.",
            "توجد قائمة بهذا الرمز بالفعل."),
    LOV_TYPE_IMMUTABLE(422, "ADMIN", "WARN",
            "This list is managed by the system and cannot be changed.",
            "هذه القائمة يديرها النظام ولا يمكن تعديلها."),
    LOV_ITEM_NOT_FOUND(404, "ADMIN", "WARN",
            "This list item was not found.",
            "عنصر القائمة غير موجود."),
    LOV_ITEM_CODE_EXISTS(409, "ADMIN", "WARN",
            "An item with this code already exists in the list.",
            "يوجد عنصر بهذا الرمز في القائمة بالفعل."),
    LOV_SYSTEM_MANAGED(422, "ADMIN", "WARN",
            "This entry is managed by the system and cannot be changed.",
            "هذا العنصر يديره النظام ولا يمكن تعديله."),
    ENDPOINT_KEY_EXISTS(409, "ADMIN", "WARN",
            "An endpoint with the key '{key}' already exists for this provider.",
            "يوجد مسار بهذا المُعرِّف '{key}' لدى هذا المزوّد بالفعل.", "key"),
    INVALID_JSON(400, "ADMIN", "WARN", false,
            "{field} is not valid JSON: {reason}",
            "الحقل {field} ليس بصيغة JSON صحيحة: {reason}", "field", "reason"),
    SECRET_ENCRYPTION_FAILED(500, "SECURITY", "CRITICAL", false,
            "The secret could not be stored securely. It has not been saved.",
            "تعذّر تخزين البيانات السرية بشكل آمن. لم يتم الحفظ."),
    SECRET_DECRYPTION_FAILED(500, "SECURITY", "CRITICAL", false,
            "A stored secret could not be read. Please re-enter it.",
            "تعذّرت قراءة بيانات سرية مخزّنة. يرجى إعادة إدخالها."),

    // ------------------------------------------------------- admin console: automation engine
    AUTOMATION_ENGINE_PAUSED(422, "ADMIN", "WARN",
            "The automation engine is paused. Resume it before asking for a run.",
            "محرك الأتمتة متوقف مؤقتاً. يرجى استئنافه قبل طلب تشغيل دورة."),
    AUTOMATION_UNKNOWN_TIMEZONE(400, "ADMIN", "WARN",
            "'{timeZone}' is not a known time zone.",
            "المنطقة الزمنية '{timeZone}' غير معروفة.", "timeZone"),
    AUTOMATION_INTERVAL_TOO_SHORT(400, "ADMIN", "WARN",
            "The shortest interval the engine will run is {minimum}.",
            "أقصر فترة يمكن للمحرك العمل بها هي {minimum}.", "minimum"),
    AUTOMATION_DAY_REQUIRED(400, "ADMIN", "WARN",
            "Choose which day of the week to run on.",
            "يرجى اختيار يوم الأسبوع الذي ستُنفَّذ فيه الدورة."),
    AUTOMATION_TIME_REQUIRED(400, "ADMIN", "WARN",
            "Choose a time of day to run at.",
            "يرجى اختيار وقت التنفيذ خلال اليوم."),
    AUTOMATION_CRON_REQUIRED(400, "ADMIN", "WARN",
            "Enter a cron expression.",
            "يرجى إدخال تعبير cron."),
    AUTOMATION_CRON_INVALID(400, "ADMIN", "WARN",
            "That is not a valid cron expression. Spring cron has six fields, starting with seconds.",
            "تعبير cron غير صالح. صيغة Spring تتكوّن من ستة حقول تبدأ بالثواني."),
    AUTOMATION_DAY_INVALID(400, "ADMIN", "WARN",
            "The day must be one of MON, TUE, WED, THU, FRI, SAT or SUN.",
            "يجب أن يكون اليوم أحد التالي: MON أو TUE أو WED أو THU أو FRI أو SAT أو SUN."),
    AUTOMATION_TIME_INVALID(400, "ADMIN", "WARN",
            "The time must be written as HH:mm on a 24-hour clock.",
            "يجب كتابة الوقت بصيغة HH:mm بنظام 24 ساعة."),
    AUTOMATION_INTERVAL_UNIT_INVALID(400, "ADMIN", "WARN",
            "The interval unit must be SECONDS, MINUTES or HOURS.",
            "وحدة الفترة يجب أن تكون SECONDS أو MINUTES أو HOURS."),
    AUTOMATION_INTERVAL_OUT_OF_RANGE(400, "ADMIN", "WARN",
            "The interval must be a positive number, and not unreasonably large.",
            "يجب أن تكون الفترة رقماً موجباً وضمن حدود معقولة."),
    AUTOMATION_MODE_REQUIRED(400, "ADMIN", "WARN",
            "Choose how often the engine should run.",
            "يرجى اختيار عدد مرات تشغيل المحرك."),
    AUTOMATION_UNKNOWN_SCHEDULE_MODE(400, "ADMIN", "WARN",
            "'{mode}' is not a schedule mode this engine supports.",
            "نمط الجدولة '{mode}' غير مدعوم في هذا المحرك.", "mode");

    private final int httpStatus;
    private final String category;
    private final String severity;
    /**
     * Whether this sentence may be shown to a customer as it is.
     *
     * <p>Separate from {@link #severity}, which says how loudly operators should hear about
     * it. "Your session has ended" is CRITICAL to monitor and entirely safe to display;
     * "The Wathq provider is not configured" is a sentence about our own deployment and
     * tells a customer nothing they can act on. When this is false the resolver substitutes
     * the generic failure message, and the specific one goes only to the logs.
     */
    private final boolean userSafe;
    private final String defaultMessageEn;
    private final String defaultMessageAr;
    /** The placeholder names both translations are expected to use. */
    private final java.util.List<String> params;

    ErrorCode(int httpStatus, String category, String severity,
              String defaultMessageEn, String defaultMessageAr, String... params) {
        this(httpStatus, category, severity, true, defaultMessageEn, defaultMessageAr, params);
    }

    ErrorCode(int httpStatus, String category, String severity, boolean userSafe,
              String defaultMessageEn, String defaultMessageAr, String... params) {
        this.httpStatus = httpStatus;
        this.category = category;
        this.severity = severity;
        this.userSafe = userSafe;
        this.defaultMessageEn = defaultMessageEn;
        this.defaultMessageAr = defaultMessageAr;
        this.params = java.util.List.of(params);
    }

    /** The wire code. Same as {@link #name()} - stated explicitly because it is a contract
     * with both portals and with every other service, not an implementation detail. */
    public String code() {
        return name();
    }

    private static final Map<String, ErrorCode> BY_CODE = Arrays.stream(values())
            .collect(Collectors.toUnmodifiableMap(ErrorCode::code, Function.identity()));

    /** Empty for a code this build does not know - an older service, or a row an operator
     * added by hand. Callers fall back to the message the exception carried. */
    public static Optional<ErrorCode> find(String code) {
        return code == null ? Optional.empty() : Optional.ofNullable(BY_CODE.get(code));
    }
}
